#!/usr/bin/env bash
# Install NGINX server, set mensaje and redirection the server
sudo apt-get update
sudo apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sed -i '/server_name _/a location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' /etc/nginx/sites-available/default
service nginx restart
