#!/usr/bin/env bash
# configures HAproxy on lb-01 server
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.5
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i '8i ENABLED=1' /etc/default/haproxy
sudo sed -i "\$a \\\nlisten 211-lb-01\n\tbind 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\tserver 211-web-01 35.237.35.49 check\n\tserver 211-web-02 34.73.18.193 check\n" /etc/haproxy/haproxy.cfg
sudo service haproxy restart