#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd, using
# the while loop + IFS.

dir="/etc/passwd"
while IFS=: read -r user pass userid groupid useridinfo home cmd;
do
    echo "The user $user is part of the $groupid gang, lives in $home and rides $cmd. $userid's place is protected by the passcode $pass, more info about the user here: $useridinfo"
done < $dir>
